sudo: required
services: 
  - docker

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-tester"
  env: "DockerTester-env"
  bucket_name: "elasticbeanstalk-us-east-1-008681416418"
  bucket_path: "docker-tester"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY